[tool.isort]
multi_line_output = 3
lines_after_imports = 2
skip = ["lib", "out"]
profile = "black"

[tool.black]
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | lib
  | out
)/
'''

[tool.ruff]
exclude = ["lib", "out", "addon_updater.py", "addon_updater_ops.py"]
ignore = [ 
    "E501", #Line too long
    ]
target-version = "py310"

[tool.mypy]
exclude = ['test_*', 'out', 'lib']
disallow_untyped_globals = false # remove this in the future

[[tool.mypy.overrides]]
module = ["bpy", "bpy.*"]
