name: Bug Report
description: Report bug, crash, problem...
body:
  - type: markdown
    attributes:
      value: |
        ### Before you report a Bug, please check the following:
        - you have the [latest version of BlenderKit](https://github.com/blenderkit/blenderkit/releases/latest) installed (latest version may have fix for your problem)
        - you have restarted the Blender after updating BlenderKit (skipping restart often causes esoteric bugs, restart can often fix your problems instantly)
        - search for similar issues in [issues](https://github.com/blenderkit/blenderkit/issues) (they can contain workarounds or solutions to fix your problem right away)

        ### Quick-help:
        These 3 steps often fixes the problem:
        1. uninstall BlenderKit
        2. install [latest version of BlenderKit](https://github.com/blenderkit/blenderkit/releases/latest) via Blender UI, using the .zip file
        3. restart Blender

        Thank you for reporting a bug! You help us to improve BlenderKit.

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: |
        Please describe the problem and expected behavior. Adding a screnshot is good, adding environment information is better, adding a complete log is the best (see below).
    value: |
      

      - BlenderKit version:
      - Blender version:
      - Operating system & architecture (x84_64, arm64...):
      - behind VPN, proxy, firewall?:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Ideally please provide a log of the problem - [How to Get Error Logs](https://www.blenderkit.com/report-bug/).
        Having the logs helps us to find the problem and deliver the fix for you much faster.
        Sometimes we are able to fix without the logs, but most of the time we will ask you for the logs anyway.
    validations:
      required: false
