name: Bug Report
description: Report a bug, crash, or other issue
body:
  - type: markdown
    attributes:
      value: |
        *Please make the title as descriptive as possible, including part of the error message if applicable. This helps other users find and relate to your issue more easily.*

        #### Before reporting a bug, please ensure the following:
        - You have installed the [latest version of Blendkit](https://github.com/blenderkit/blenderkit/releases/latest), as the latest release may include a fix for your issue.
        - You have restarted Blender after updating Blendkit. Skipping a restart can lead to unusual bugs; a restart often resolves issues immediately.
        - You have searched for similar issues in the [Blendkit issues](https://github.com/blenderkit/blenderkit/issues). Existing threads may offer workarounds or solutions.

        #### 3-Step Quick Help:
        1. Uninstall Blendkit.
        2. Install the [latest version of Blendkit](https://github.com/blenderkit/blenderkit/releases/latest) via Blender's UI, using the .zip file.
        3. Restart Blender.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: |
        Please describe the problem, the expected behavior, and any deviation from it.
        The development team needs to understand and reproduce the problem from your description in order to fix it.
        If the problem is tied to your account, please provide an email under which you log in to Blendkit.com.
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: |
        Additional information about your OS and your system environment.
        Which versions of add-on and Blender do you use?
        Which operating system are you on?
        Do you have any antivirus or firewall enabled?
        Is your computer behind corporate proxy?
      value: |
        ### Environment Information - Bug happens on:
        - Blendkit version: v3.y.z
        - Blender version: vX.Y.Z
        - How was Blender installed? (Installer from blender.org, from Microsoft Store, Steam etc.)
        - Operating system & architecture: Windows11/Windows10 (x86_64/ARM64), MacOS (Intel/Apple Silicon), Debian/Ubuntu/Fedora... (x86_64/ARM64)
        - Are you using VPN, proxy, or firewall?
        - Are you behind corporate proxy or in state censoring/controlling internet traffic?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        Ideally, please provide the error logs related to the problem. [Here's how to get error logs](https://www.blendkit.com/report-bug/).
        Providing error logs enables us to diagnose and address the issue more efficiently.
        We may be able to resolve the issue without the logs, but in most cases, we will request them.
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug! Your input helps us improve Blendkit.
