name: main-push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: pip install -r devs/requirements.txt
      - name: ISORT
        run: python -m isort . --check-only --diff
        continue-on-error: true
      - name: BLACK
        run: python -m black . --check --diff
      #- name: RUFF on ./daemon
      #  run: python -m ruff daemon
      - name: Server set to production
        run: python3 -c 'from global_vars import SERVER; assert SERVER == "https://www.blenderkit.com"'

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './client/go.mod'
          cache-dependency-path: './client/go.sum'
        id: go
      - name: Build add-on
        run: python dev.py build
      - name: Store the build
        uses: actions/upload-artifact@v4
        with:
          name: blenderkit-${{ github.ref_name }}-${{ github.sha }}
          path: |
            out
            !out/blenderkit.zip

  make-tests-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: python .github/make-tests-matrix.py >> $GITHUB_OUTPUT
 
  TESTS:
    needs: make-tests-matrix
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.make-tests-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './client/go.mod'
          cache-dependency-path: './client/go.sum'
        id: go
      - name: Cache Blender
        id: blenderBinaryCache
        uses: actions/cache@v4
        with:
          path: /home/runner/blender
          key: blender-${{matrix.version}}-${{matrix.sha}}
      - name: Download Blender
        if: steps.blenderBinaryCache.outputs.cache-hit != 'true'
        run: curl ${{ matrix.download_url }} -o /home/runner/blender.tar.xz
      - name: Mkdir
        run: mkdir {/home/runner/.local/bin,/home/runner/blender} -p
      - name: Extract Blender
        if: steps.blenderBinaryCache.outputs.cache-hit != 'true'
        run: tar -xf /home/runner/blender.tar.xz -C /home/runner/blender --strip-components=1
      - name: Add Blender to PATH
        run: ln -s /home/runner/blender/blender /home/runner/.local/bin/blender
      - name: TEST
        run: python dev.py test --install-at /home/runner/.config/blender/${{matrix.version_x_y}}/scripts/addons
