name: main-push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: pip install -r devs/requirements.txt
      - name: ISORT
        run: python -m isort . --check-only --diff
        continue-on-error: true
      - name: BLACK
        run: python -m black . --check --diff
      - name: Server set to production
        run: python3 -c 'from global_vars import SERVER; assert SERVER == "https://www.blenderkit.com"'

  Versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check CLIENT_VERSION
        run: python -c 'from global_vars import CLIENT_VERSION; VERSION = open("client/VERSION").read().strip(); assert CLIENT_VERSION == f"v{VERSION}", "CLIENT_VERSION does not match the content of client/VERSION"'
      - name: Check add-on VERSION
        run: python -c "import re; f = open('__init__.py'); bl_info_version = re.search(r'\"version\":\s*(\(.*?\))', f.read()).group(1); f.seek(0); VERSION = re.search(r'VERSION =\s*(\(.*?\))', f.read()).group(1); f.close(); assert bl_info_version == VERSION"
      - name: Check blender_manifest.toml
        run: python -c "import re; f = open('__init__.py'); match = re.search(r'VERSION\s+=\s+\((\d+),\s+(\d+),\s+(\d+),\s+(\d{6})\)', f.read()); VERSION = (match.group(1), match.group(2), match.group(3), match.group(4)); f.close(); m = open('blender_manifest.toml'); match = re.search(r'version\s+=\s+\"(\d+)\.(\d+)\.(\d+)-(\d{6})\"', m.read()); manifest_version = (match.group(1), match.group(2), match.group(3), match.group(4)); m.close(); assert manifest_version == VERSION"

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './client/go.mod'
          cache-dependency-path: './client/go.sum'
        id: go
      - name: Build add-on
        run: python dev.py build
      - name: Store the build
        uses: actions/upload-artifact@v4
        with:
          name: blenderkit-${{ github.ref_name }}-${{ github.sha }}
          path: |
            out
            !out/blenderkit.zip

  make-tests-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: python .github/make-tests-matrix.py >> $GITHUB_OUTPUT
 
  TESTS:
    needs: make-tests-matrix
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.make-tests-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './client/go.mod'
          cache-dependency-path: './client/go.sum'
        id: go
      - name: Cache Blender
        id: blenderBinaryCache
        uses: actions/cache@v4
        with:
          path: /home/runner/blender
          key: blender-${{matrix.version}}-${{matrix.sha}}
      - name: Download Blender
        if: steps.blenderBinaryCache.outputs.cache-hit != 'true'
        run: curl ${{ matrix.download_url }} -o /home/runner/blender.tar.xz
      - name: Mkdir
        run: mkdir {/home/runner/.local/bin,/home/runner/blender} -p
      - name: Extract Blender
        if: steps.blenderBinaryCache.outputs.cache-hit != 'true'
        run: tar -xf /home/runner/blender.tar.xz -C /home/runner/blender --strip-components=1
      - name: Add Blender to PATH
        run: ln -s /home/runner/blender/blender /home/runner/.local/bin/blender
      - name: TEST
        run: python dev.py test --install-at /home/runner/.config/blender/${{matrix.version_x_y}}/scripts/addons
